name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: SSH 키 설정
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: 서버에 배포 및 서비스 재시작
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ~/.ssh/id_rsa
          port: 22
          script: |
            cd /home/dldbsxo02/Welcome-MJSEC-3rd
            source venv/bin/activate
            git pull origin main
            # Flask 서비스 재시작
            sudo systemctl daemon-reload
            sudo systemctl restart flask
            # Nginx 설정 문법 검사 & 재적용
            sudo nginx -t
            sudo systemctl reload nginx
