- name: Checkout code
  uses: actions/checkout@v4

- name: Start ssh-agent and add key
  uses: webfactory/ssh-agent@v0.5.3
  with:
    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

- name: Add host to known_hosts
  run: ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

- name: Deploy to server
  run: |
    set -eux
    # deploy_key 대신 gcp_gh_actions 사용
    ssh -i ~/.ssh/gcp_gh_actions -o StrictHostKeyChecking=yes \
        "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" << 'EOF'
      cd /home/dldbsxo02/Welcome-MJSEC-3rd
      git pull origin main
      source venv/bin/activate
      sudo systemctl daemon-reload
      sudo systemctl restart flask
      sudo nginx -t
      sudo systemctl reload nginx
    EOF
