name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) ssh-agent 에 개인키 로드
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3) 서버 호스트키 등록
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      # 4) SSH 접속 후 배포 스크립트 실행
      - name: Deploy to Server
        run: |
          set -eux
          ssh -o StrictHostKeyChecking=no \
              "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" << 'EOF'
            cd /home/dldbsxo02/Welcome-MJSEC-3rd
            git pull origin main
            source venv/bin/activate
            sudo systemctl daemon-reload
            sudo systemctl restart flask
            sudo nginx -t
            sudo systemctl reload nginx
          EOF
