name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. SSH 디렉터리 초기화
      - name: Cleanup old SSH directory
        run: |
          # ~/.ssh 가 파일이거나 디렉터리로 남아 있어도 강제 삭제
          rm -rf ~/.ssh
          mkdir -p ~/.ssh

      # 3. 개인키 저장
      - name: Save SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 4. 서버 호스트키 등록
      - name: Add server to known_hosts
        run: ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      # 5. 원격 서버에 배포 스크립트 실행
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ~/.ssh/id_rsa
          port: 22
          script: |
            set -eux
            cd /home/dldbsxo02/Welcome-MJSEC-3rd
            git pull origin main
            source venv/bin/activate
            sudo systemctl daemon-reload
            sudo systemctl restart flask
            sudo nginx -t
            sudo systemctl reload nginx
