name: Deploy to Server

# main 브랜치에 푸시될 때 실행
on:
  push:
    branches:
      - main

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. SSH 키 및 known_hosts 설정
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      # 3. 서버 접속 후 배포 스크립트 실행
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ~/.ssh/id_rsa
          port: 22
          script: |
            # 프로젝트 디렉터리로 이동
            cd /home/dldbsxo02/Welcome-MJSEC-3rd

            # 최신 코드 가져오기
            git pull origin main

            # 가상환경 활성화 (필요한 경우)
            source venv/bin/activate

            # Flask 서비스 재시작
            sudo systemctl daemon-reload
            sudo systemctl restart flask

            # Nginx 문법 검사 및 재시작
            sudo nginx -t
            sudo systemctl reload nginx
